// import './example/01_simple'
// import './example/02_simple'
// import './example/03_simple'
// import './example/04_error'
// import './example/05_extend'
// import './example/06_interceptors'
// import './example/07_config'
// import './example/08_cancel'
import './example/09_withCredentials'