// import './example/01_simple'
// import './example/02_simple'
// import './example/03_simple'
// import './example/04_error'
// import './example/05_extend'
// import './example/06_interceptors'
// import './example/07_config'
// import './example/08_cancel'
// import './example/09_withCredentials'
// import './example/10_cookie'
// import './example/11_upload&download'
// import './example/12_auth'
// import './example/13_304'
// import './example/14_serializer'
// import './example/15_baseURL'
import './example/16_实例方法'